"""Create shell-executable plans for generative omni CLI experiments.

Some experimental multimodal llama.cpp CLIs behave differently when launched
from Python subprocesses.  This script keeps Python responsible for deterministic
case construction only, then writes a shell script that can be executed directly
from a terminal/WSL shell.  The raw model outputs are parsed by
``generative_omni_parse_outputs.py``.
"""

from __future__ import annotations

import argparse
import json
import random
import shlex
from pathlib import Path
from typing import Any

from generative_omni_policy_smoke import POLICIES, build_options, build_prompt, read_jsonl


def shell_quote(path_or_text: str) -> str:
    return shlex.quote(path_or_text)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--run-script", required=True)
    parser.add_argument("--llama-cli", default="llama-mtmd-cli")
    parser.add_argument("--model", required=True)
    parser.add_argument("--mmproj")
    parser.add_argument("--policy", choices=sorted(POLICIES), default="raw")
    parser.add_argument("--audio-field", default="audio_path")
    parser.add_argument("--label-field", default="intent")
    parser.add_argument("--text-field", default="text")
    parser.add_argument("--max-samples", type=int, default=8)
    parser.add_argument("--candidate-count", type=int, default=4)
    parser.add_argument("--timeout-s", type=int, default=180)
    parser.add_argument("--max-tokens", type=int, default=16)
    parser.add_argument("--ctx-size", type=int, default=1024)
    parser.add_argument("--gpu-layers", default="auto")
    parser.add_argument("--prompt-mode", choices=["letter", "json", "anti_answer"], default="anti_answer")
    parser.add_argument("--flatten-prompt", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--log-disable", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    rows = read_jsonl(Path(args.manifest))
    rows = [r for r in rows if r.get(args.audio_field) and r.get(args.label_field)]
    universe = sorted({str(r[args.label_field]) for r in rows})
    rng = random.Random(args.seed)
    selected = rows[: args.max_samples]

    output_dir = Path(args.output_dir)
    raw_dir = output_dir / "raw"
    raw_dir.mkdir(parents=True, exist_ok=True)
    cases_path = output_dir / "cases.jsonl"
    run_script = Path(args.run_script)
    run_script.parent.mkdir(parents=True, exist_ok=True)

    cases: list[dict[str, Any]] = []
    labels = "ABCDEFGH"
    for idx, row in enumerate(selected):
        gold = str(row[args.label_field])
        options, gold_letter = build_options(
            gold=gold,
            universe=universe,
            candidate_count=min(args.candidate_count, len(labels)),
            rng=rng,
        )
        prompt = build_prompt(args.policy, options, args.prompt_mode, args.flatten_prompt)
        raw_path = raw_dir / f"case_{idx:04d}.txt"
        cases.append(
            {
                "case_id": f"case_{idx:04d}",
                "sample_id": row.get("sample_id"),
                "policy": args.policy,
                "gold": gold,
                "gold_letter": gold_letter,
                "options": options,
                "prompt": prompt,
                "raw_output_path": str(raw_path),
                "audio_path": row.get(args.audio_field),
                "source_text": row.get(args.text_field),
            }
        )

    with cases_path.open("w", encoding="utf-8") as f:
        for case in cases:
            f.write(json.dumps(case, ensure_ascii=False) + "\n")

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by scripts/generative_omni_cli_plan.py",
        "# This file may contain local model paths and should stay under ignored outputs/.",
        "",
    ]
    for case in cases:
        cmd = [
            args.llama_cli,
            "-m",
            args.model,
        ]
        if args.mmproj:
            cmd.extend(["--mmproj", args.mmproj])
        cmd.extend(
            [
                "--audio",
                str(case["audio_path"]),
                "-p",
                str(case["prompt"]),
                "-n",
                str(args.max_tokens),
                "--temp",
                "0",
                "--ctx-size",
                str(args.ctx_size),
                "--gpu-layers",
                args.gpu_layers,
            ]
        )
        if args.log_disable:
            cmd.append("--log-disable")
        rendered = " ".join(shell_quote(part) for part in cmd)
        lines.append(f"echo 'running {case['case_id']}'")
        lines.append(f"timeout {int(args.timeout_s)}s {rendered} > {shell_quote(case['raw_output_path'])} 2>&1 || true")
        lines.append("")

    run_script.write_text("\n".join(lines), encoding="utf-8")
    result = {
        "cases": len(cases),
        "cases_path": str(cases_path),
        "run_script": str(run_script),
        "raw_dir": str(raw_dir),
    }
    (output_dir / "plan_summary.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
